const itemMap = {
  'Silk Scarf': '丝绸围巾',
  'Black Belt': '黑带',
  'Sharp Beak': '锐利鸟嘴',
  'Poison Barb': '毒针',
  'Soft Sand': '柔软沙子',
  'Hard Stone': '硬石头',
  'Silver Powder': '银粉',
  'Spell Tag': '诅咒之符',
  'Metal Coat': '金属膜',
  'Charcoal': '木炭',
  'Mystic Water': '神秘水滴',
  'Miracle Seed': '奇迹种子',
  'Magnet': '磁铁',
  'Twisted Spoon': '弯曲的汤匙',
  'Never-Melt Ice': '不融冰',
  'Dragon Fang': '龙之牙',
  'Black Glasses': '黑色眼镜',
  'Fairy Feather': '妖精之羽',
  'HP Up': 'ＨＰ增强剂',
  'Protein': '攻击增强剂',
  'Iron': '防御增强剂',
  'Calcium': '特攻增强剂',
  'Zinc': '特防增强剂',
  'Carbos': '速度增强剂',
  'Rare Candy': '神奇糖果',
  'Rarer Candy': '稀有糖果',
  'Mega Bracelet': '超级手镯',
  'Dynamax Band': '极巨腕带',
  'Tera Orb': '太晶珠',
  'Map': '地图',
  'Potion': '伤药',
  'Super Potion': '好伤药',
  'Hyper Potion': '厉害伤药',
  'Max Potion': '全满药',
  'Full Restore': '全复药',
  'Revive': '活力碎片',
  'Max Revive': '活力块',
  'Full Heal': '万灵药',
  'Sacred Ash': '圣灰',
  'Reviver Seed': '复活草',
  'Ether': 'ＰＰ单项小补剂',
  'Max Ether': 'ＰＰ单项全补剂',
  'Elixir': 'ＰＰ多项小补剂',
  'Max Elixir': 'ＰＰ多项全补剂',
  'PP Up': 'ＰＰ提升剂',
  'PP Max': 'ＰＰ极限提升剂',
  'Lure': '引虫香水',
  'Super Lure': '白银香水',
  'Max Lure': '黄金香水',
  'Memory Mushroom': '记忆蘑菇',
  'EXP. All': '学习装置',
  'EXP. Balance': '平衡秤',
  'Oval Charm': '圆形护符',
  'EXP. Charm': '经验护符',
  'Super EXP. Charm': '超级经验护符',
  'Golden EXP. Charm': '黄金经验护符',
  'Lucky Egg': '幸运蛋',
  'Golden Egg': '黄金蛋',
  'Soothe Bell': '安抚之铃',
  'Soul Dew': '心之水滴',
  'Nugget': '金珠',
  'Big Nugget': '巨大金珠',
  'Relic Gold': '古代金币',
  'Amulet Coin': '护符金币',
  'Golden Punch': '黄金拳',
  'Coin Case': '代币盒',
  'Lock Capsule': '上锁的容器',
  'Grip Claw': '紧缠钩爪',
  'Wide Lens': '广角镜',
  'Multi Lens': '多重镜片',
  'Healing Charm': '治愈护符',
  'Candy Jar': '糖果罐',
  'Berry Pouch': '树果袋',
  'Focus Band': '气势头带',
  'King\'s Rock': '王者之证',
  'Leftovers': '吃剩的东西',
  'Shell Bell': '贝壳之铃',
  'Baton': '接力棒',
  'Shiny Charm': '闪光护符',
  'Ability Charm': '特性护符',
  'IV Scanner': '个体值扫描仪',
  'DNA Splicers': '基因之楔',
  'Mini Black Hole': '迷你黑洞',
  'Damage Token': '伤害令牌',
  'Protection Token': '保护令牌',
  'Recovery Token': '再生令牌',
  'Poison Token': '毒药令牌',
  'Paralyze Token': '麻痹令牌',
  'Sleep Token': '睡眠令牌',
  'Freeze Token': '冻结令牌',
  'Burn Token': '燃烧令牌',
  'Full Heal Token': '痊愈令牌',
  'Endure Token': '忍耐令牌',
  'Fusion Token': '融合令牌',
  'Sitrus Berry': '柑果',
  'Lum Berry': '亮光果',
  'Enigma Berry': '神秘果',
  'Liechi Berry': '荔枝果',
  'Ganlon Berry': '龙睛果',
  'Petaya Berry': '火龙果',
  'Apicot Berry': '杏仔果',
  'Salac Berry': '沙鳞果',
  'Lansat Berry': '蓝橘果',
  'Starf Berry': '星桃果',
  'Leppa Berry': '零余果',
  'X Attack': '力量强化',
  'X Defense': '防御强化',
  'X Sp. Atk': '特攻强化',
  'X Sp. Def': '特防强化',
  'X Speed': '速度强化',
  'X Accuracy': '命中强化',
  'Dire Hit': '要害攻击',
};

export function getItemName(text: string) {
  return itemMap[text] ?? text;
}